sat: sat.c
	gcc -g -Wall -std=gnu99 sat.c -lm -o sat

automata: automata.c
	gcc -g -Wall -std=gnu99 automata.c -lm -o automata
	@echo "Usage: ./automata <initial_gen> <rule> <num_generations>";
clean:
	rm -f sat 
